---
- name: Side effect
  hosts: all
  tasks:
    - name: Import defaults and vars from zabbix_agent role
      ansible.builtin.include_role:
        name: zabbix_agent
        tasks_from: init
        public: true
      vars:
        verification: true
    - name: 'Variables : Include system and disrtibution specific'
      ansible.builtin.include_vars: '../../roles/zabbix_agent/vars/{{ var_item }}.yml'
      loop: '{{ var_list | select }}'
      loop_control:
        loop_var: var_item
      vars:
        var_list:
          - '{{ "ubuntu" if ansible_distribution == "Ubuntu" else None }}'
          - '{{ "debian" if ansible_distribution == "Debian" else None }}'
          - '{{ "redhat" if ansible_distribution in ["RedHat", "AlmaLinux", "Rocky", "CentOS", "OracleLinux"] else None }}'
    - name: Include OS packager(yum/apt) specific tasks
      ansible.builtin.include_tasks: '../../roles/zabbix_agent/tasks/{{ ansible_os_family | lower }}.yml'
      vars:
        agent_minor_version: false
        package_state: latest
