---
# Collections used in "zabbix_agent" role.
collections:
  - name: ansible.utils
    version: '>=2.8.0'
  - name: ansible.posix
    version: '>=1.4.0'
  - name: ansible.netcommon
    version: '>=3.1.1'
