---
- name: Upload certificates
  hosts: all
  tasks:
    - name: Upload certs
      become: true
      ansible.builtin.copy:
        src: '{{ tls_file.source }}'
        dest: '{{ tls_file.target }}'
        mode: 'u=rwx,g=rwx,o=rwx'
        directory_mode: 'u=rwx,g=rwx,o=rwx'
        # recursive: true
      loop_control:
        loop_var: tls_file
      loop: '{{ agent_tls_file_list | select }}'
      vars:
        agent_tls_file_list:
          - {source: "../default/files/certs/ca.crt", target: "{{ param_tlscafile }}"}
          - {source: "../default/files/certs/{{ inventory_hostname }}.crt", target: "{{ param_tlscertfile }}"}
          - {source: "../default/files/certs/{{ inventory_hostname }}.key", target: "{{ param_tlskeyfile }}"}

- name: "Testing role zabbix_agent: {{ test_name }}"
  hosts: all
  pre_tasks:
    - name: Include all from vars folder
      ansible.builtin.include_vars:
        dir: vars
        ignore_unknown_extensions: true
        extensions:
          - 'yaml'
          - 'yml'
      tags: [always]
  roles:
    - role: zabbix_agent
    - role: host
      tags: [never, host]
      host_zabbix_api_port: 8070
