---
### Verify playbook does not inherit role defaults and vars. To make it happen import the role tasks.
- name: Verify
  hosts: all
  tasks:
    - name: Import defaults, vars and verification tasks from zabbix_agent role
      when: >-
        "remove" not in ansible_run_tags
      ansible.builtin.include_role:
        name: zabbix_agent
        tasks_from: verify
        # public: true
      vars:
        zabbix_agent_verification: false
        source_tlscafile: "../default/files/certs/ca.crt"
        source_tlscertfile: "../default/files/certs/{{ inventory_hostname }}.crt"
        source_tlskeyfile: "../default/files/certs/{{ inventory_hostname }}.key"
      tags: [skip_ansible_lint]
