---
############################################################################################################################################
# host_hostgroups '{{ group_names + ["SUper GROUP"] }}'
host_templates: ["Linux by Zabbix agent"]
# host_templates: ["Linux by Zabbix agent active"]
host_name: '{{ inventory_hostname }}'
host_tags: '{{ [{"tag": "variant", "value": agent_variant},{"tag" "managed"}] }}'
host_interfaces:
  - type: agent
    dns: host.containers.internal
    useip: false
    port: '{{ ext_agent_port if (agent_variant is not defined or agent_variant | string == "1") else ext_agent_port2 }}'
