---
- name: Certsgen
  hosts: all
  tasks:
    - name: Generate certificates for testing
      ansible.builtin.script: ../default/files/certsgen.sh {{ ansible_play_hosts_all | join(' ') }}
      delegate_to: localhost
      run_once: true
      tags: [always]
