{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

### Disable excess services startup
RUN rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;

### Re/install systemd & dbus
RUN yum makecache && yum --assumeyes reinstall systemd dbus util-linux firewalld && yum clean all \
    || yum makecache && yum --assumeyes install systemd dbus util-linux firewalld && yum clean all

CMD ["/usr/sbin/init"]